### ISSUE TITLE
Create Archive directory if it doesn't exist

### ISSUE THREAD

**Issue by briansuhr** [andrewlrogers/srvy#10]
Create Archive directory on initial setup.py configuration.

**Comment by andrewlrogers** [comment]
We can change configuration/setup_db.py to do it. Maybe even create an install program that would:

- [ ] Create the database

- [ ] Create the Archive directory

- [ ] Populate the config file with custom parameter based on raw input

- [ ] Configure the crontab job.

**Comment by briansuhr** [comment]
I like that idea. We can also use a .gitignore file in the archive with the following code:
```

*
*/
!.gitignore
```

It will ignore all files in the directory but keep the directory itself.
