### ISSUE TITLE
background_colors in config.parser stored as string

### ISSUE THREAD

**Issue by andrewlrogers** [andrewlrogers/srvy#11]
When calling 
`background_color = parser.get('colors', 'background_color')`
it returns a string instead of a list
`'[(0,0,0), (50,50,50), (153,153,153)]'`
So when I do 
`random.choice(background_color)`
it reutrns `[` or `5` instead of the tuple.

Need to change the parser to create a list instead of a string.

**Comment by briansuhr** [comment]
Would ast.literal_eval() work? 

See _[Converting a string representation of a list into an actual list object](https://stackoverflow.com/questions/10775894/converting-a-string-representation-of-a-list-into-an-actual-list-object)_.
