### ISSUE TITLE
Use relative filepath for questions.txt download

### ISSUE THREAD

**Issue by briansuhr** [andrewlrogers/srvy#6]
Will a relative filepath work for downloading questions.txt to the pi, instead of using /home/pi/srvy/synch/questions.txt? Relative path will make it easier to test on non-pi systems.

**Comment by briansuhr** [comment]
@andrewlrogers is this done?

**Comment by andrewlrogers** [comment]
I changed to a relative file path, but the questions are stored and pulled as a csv
