### ISSUE TITLE
Add delay between questions

### ISSUE THREAD

**Issue by briansuhr** [andrewlrogers/srvy#7]
Should there be a delay between questions to discourage the same person from answering multiple times? For instance, the screen could show a "Thank you!" message after a response, which disappears after 60 seconds.

**Comment by andrewlrogers** [comment]
60 seconds seems like a long time. I currently have 5 seconds to prevent button smashing. 

Do you think we should add this as a configuration variable?

**Comment by briansuhr** [comment]
Yeah let's put it as a variable.
